version: '3.8'

services:
  # This is GITLAB Server instance
  gitlab:
    container_name: gitlab
    image: "${GITLAB_IMAGE}"
    restart: unless-stopped
    hostname: "${GITLAB_HOSTNAME}"
    extra_hosts:
      - "${GITLAB_EXTRA_HOST_1}"
      - "${GITLAB_EXTRA_HOST_2}"
      - "${GITLAB_EXTRA_HOST_3}"
    networks:
      net:
        ipv4_address: "${GITLAB_IPV4_ADDRESS}"
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 15m
      timeout: 100s
      retries: 3
      start_period: 15m
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_openssl_verify_mode'] = '${SMTP_OPENSSL_VERIFY_MODE}'
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - "config:/etc/gitlab"
      - "logs:/var/log/gitlab"
      - "data:/var/opt/gitlab"
    shm_size: "${GITLAB_SHARED_MEMORY}"

  # This is RUNNER
  gitlab-runner:
    container_name: gitlab-runner
    image: "${GITLAB_RUNNER_IMAGE}"
    restart: unless-stopped
    extra_hosts:
      - "${GITLAB_EXTRA_HOST_1}"
      - "${GITLAB_EXTRA_HOST_3}"
    volumes:
      - "runner_conf:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      net:
        ipv4_address: "${GITLAB_RUNNER_IPV4_ADDRESS}"

  # MAIL
  maildev:
    container_name: maildev
    image: "${MAILDEV_IMAGE}"
    hostname: "${MAILDEV_HOSTNAME}"
    restart: unless-stopped
    extra_hosts:
      - "${GITLAB_EXTRA_HOST_1}"
    networks:
      net:
        ipv4_address: "${MAILDEV_IPV4_ADDRESS}"
    ports:
      - "${MAILDEV_WEB_PORT}:1080" # maildev - web application
      - "${MAILDEV_SMTP_PORT}:1025" # will use 'mail:1025' to send emails

# ALL options(network + volume)
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_SUBNET}"

volumes:
  config:
  logs:
  data:
  runner_conf: