name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo print
        run: echo "Echo hello world"
       
      - name: Create artifact
        run: |
          mkdir build
          echo "Hello" > build/file.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build
          path: build/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test after build"
  
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy after build and test"