name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use env
      run: echo "Environment: ${{ env.NODE_ENV }}"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test after build"
  
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy after build and test"